"""Local development helpers."""

import os
import subprocess
import sys
from pathlib import Path

import click

from deploy import docker
from deploy.utils import timing


FRONTEND_DIR = "aiarena/frontend-spa"


@click.group()
def dev():
    """Local development commands."""


@dev.command("manage-py", help="Run a Django management command in the dev container")
@click.argument("command", type=str, default="--help")
def manage_py(command):
    docker.cli(f"exec -i aiarena_dev bash -c 'cd /code/ && python manage.py {command}'")


@dev.command("build-image", help="Build dev image")
@timing
def build_image():
    tag = {"latest"}
    docker.build_image("env", tag)
    docker.build_image("dev", tag)


def get_git_root() -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True,
        text=True,
        check=True,
    )
    return Path(result.stdout.strip())


def run_check(name: str, command: list[str], cwd: Path, env: dict | None = None) -> bool:
    click.echo(f"\n{name}")
    result = subprocess.run(command, check=False, cwd=cwd, env=env)
    return result.returncode == 0


@dev.command("pre-commit", help="Run all pre-commit checks (matches CI)")
def pre_commit():
    """Run all checks that gate a commit. This is also what CI runs.

    Runs every check even if one fails, so you see all issues in one pass.
    Exits 2 on any failure.
    """
    git_root = get_git_root()
    frontend = git_root / FRONTEND_DIR
    django_env = {**os.environ, "DJANGO_ENVIRONMENT": "DEVELOPMENT"}

    checks = [
        ("Ruff check...", ["uv", "run", "ruff", "check"], git_root, None),
        ("Ruff format check...", ["uv", "run", "ruff", "format", "--check"], git_root, None),
        (
            "Generating GraphQL schema...",
            ["uv", "run", "python", "manage.py", "graphql_schema"],
            git_root,
            django_env,
        ),
        ("Relay compiler...", ["npm", "run", "relay"], frontend, None),
        ("ESLint...", ["npm", "run", "lint"], frontend, None),
        ("TypeScript check...", ["npm", "run", "typescript"], frontend, None),
    ]

    failed = False
    for name, command, cwd, env in checks:
        if not run_check(name, command, cwd, env):
            failed = True

    sys.exit(2 if failed else 0)


@dev.command("setup-git-hooks", help="Install git pre-commit hook")
def setup_git_hooks():
    """Install a pre-commit hook that runs `uv run dev pre-commit`."""
    git_root = get_git_root()
    pre_commit_hook = git_root / ".git" / "hooks" / "pre-commit"

    hook_content = """#!/bin/sh
# Auto-generated by `uv run dev setup-git-hooks`

uv run dev pre-commit
"""

    if pre_commit_hook.is_symlink():
        pre_commit_hook.unlink()

    pre_commit_hook.write_text(hook_content)
    pre_commit_hook.chmod(0o755)

    click.echo(f"Installed pre-commit hook at {pre_commit_hook}")
