repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: uv run black --check
        types: [python]
        language: python
      - id: ruff
        name: ruff
        entry: uv run ruff
        types: [python]
        language: python