repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff formatting
        entry: uv run ruff format --check --diff
        types: [python]
        language: python
      - id: ruff-lint
        name: ruff linting
        entry: uv run ruff check --output-format=github .
        types: [python]
        language: python