# Generated by Django 3.0.8 on 2021-11-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patreon", "0002_patreonaccountbind"),
    ]

    operations = [
        migrations.AddField(
            model_name="patreonaccountbind",
            name="last_token_refresh_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patreonaccountbind",
            name="last_token_refresh_failure",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patreonaccountbind",
            name="last_token_refresh_failure_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patreonaccountbind",
            name="last_token_refresh_success",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
