# Generated by Django 3.2.9 on 2022-08-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patreon", "0003_auto_20211112_1942"),
    ]

    operations = [
        migrations.AddField(
            model_name="patreonaccountbind",
            name="patreon_user_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
