# Generated by Django 3.2.9 on 2022-08-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patreon', '0005_patreonunlinkeddiscorduids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patreonunlinkeddiscorduids',
            name='discord_uid',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='patreonunlinkeddiscorduids',
            name='patreon_user_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
