CREATE USER IF NOT EXISTS aiarena IDENTIFIED BY 'aiarena';
CREATE DATABASE IF NOT EXISTS aiarena;
GRANT ALL PRIVILEGES ON aiarena.* TO aiarena WITH GRANT OPTION;
CREATE DATABASE IF NOT EXISTS test_aiarena;
GRANT ALL PRIVILEGES ON test_aiarena.* TO aiarena WITH GRANT OPTION;