import re

from django.conf import settings
from django.core.management.base import BaseCommand
from django.urls import NoReverseMatch, URLPattern, URLResolver, get_resolver, reverse


OUTPUT_PATH = settings.BASE_DIR / "aiarena/frontend-spa/src/__generated__/urlDefinitions.ts"

# The goal is parity with Django's `reverse` — generate every URL the frontend could
# legitimately link to. Only the genuinely un-linkable internal tooling is excluded:
# the Django admin and the debug toolbar (large, namespaced, never reachable from the SPA).
EXCLUDED_NAMESPACES = frozenset({"admin", "djdt"})


class Command(BaseCommand):
    help = "Generate TypeScript URL definitions for the SPA from Django's urls.py"

    def handle(self, *args, **options):
        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

        urls = self._extract_urls()
        OUTPUT_PATH.write_text(self._generate_typescript(urls))

        self.stdout.write(self.style.SUCCESS(f"Generated URL definitions at {OUTPUT_PATH}"))

    def _extract_urls(self) -> list[tuple[str, str, list[str]]]:
        """Discover every named route as a (full_name, path, param_names) tuple.

        The path is produced by `reverse()` itself — with a sentinel substituted for each
        param and then swapped back to a `<param>` placeholder — so the generated URL is
        Django's reverse output by construction, not a reconstruction that could drift from
        it. (A Playwright test asserts exactly this parity against the browser helper.)
        """
        names_to_params: dict[str, list[str]] = {}
        self._collect_names(get_resolver(), namespace="", names_to_params=names_to_params)

        urls: list[tuple[str, str, list[str]]] = []
        for full_name, params in names_to_params.items():
            path = self._reverse_to_template(full_name, params)
            if path is not None:
                urls.append((full_name, path, params))
        return urls

    def _collect_names(
        self,
        resolver: URLResolver,
        namespace: str,
        names_to_params: dict[str, list[str]],
    ) -> None:
        if resolver.namespace:
            namespace = f"{namespace}:{resolver.namespace}" if namespace else resolver.namespace

        if namespace.split(":", 1)[0] in EXCLUDED_NAMESPACES:
            return

        for pattern in resolver.url_patterns:
            if isinstance(pattern, URLResolver):
                self._collect_names(pattern, namespace, names_to_params)
            elif isinstance(pattern, URLPattern) and pattern.name:
                full_name = f"{namespace}:{pattern.name}" if namespace else pattern.name
                params = list(getattr(pattern.pattern, "converters", {}).keys())
                if not params:
                    params = re.findall(r"\(\?P<(\w+)>", pattern.pattern.regex.pattern)
                # DRF routers register a `.<format>` suffix variant of every route under the
                # same name. The SPA only ever wants the canonical path, so skip the suffix.
                if "format" in params:
                    continue
                # A name can resolve to several patterns (e.g. a DRF `api-root` mounted under
                # several prefixes). `reverse()` picks the canonical one; we just need the
                # name and its params, so first-seen is fine.
                names_to_params.setdefault(full_name, params)

    def _reverse_to_template(self, name: str, params: list[str]) -> str | None:
        """`reverse(name)` with each param replaced by a `<param>` placeholder.

        Returns None if the route can't be reversed with simple sentinel values (e.g. a
        converter the sentinels don't satisfy) — such routes aren't usefully linkable by
        name from the frontend anyway.
        """
        # Unique all-digit sentinels: digits satisfy the common int/str/slug/path
        # converters, and being unique they map back to their param unambiguously.
        sentinels = {param: str(90000 + i) for i, param in enumerate(params)}
        try:
            path = reverse(name, kwargs=sentinels)
        except NoReverseMatch:
            return None
        for param, sentinel in sentinels.items():
            path = path.replace(sentinel, f"<{param}>")
        return path

    def _generate_typescript(self, urls: list[tuple[str, str, list[str]]]) -> str:
        urls.sort(key=lambda url: url[0])

        lines = [
            "// Auto-generated by `python manage.py generate_url_definitions`.",
            "// Do not edit manually; regenerate with `uv run dev pre-commit`.",
            "",
            "export const URL_DEFINITIONS = {",
        ]
        for full_name, path, _params in urls:
            lines.append(f'  "{full_name}": "{path}",')
        lines += [
            "} as const;",
            "",
            "export type UrlName = keyof typeof URL_DEFINITIONS;",
            "",
            "export type UrlParams = {",
        ]
        for full_name, _path, params in urls:
            if params:
                fields = ", ".join(f"{param}: string | number" for param in params)
                lines.append(f'  "{full_name}": {{ {fields} }};')
            else:
                lines.append(f'  "{full_name}": Record<string, never>;')
        lines += ["};", ""]

        return "\n".join(lines)
