FROM aiarena/env

ARG SECRET_KEY

ADD ./aiarena/unit-config.json /docker-entrypoint.d/
RUN chown -R unit:unit /app/

ADD ./pip/requirements.PRODUCTION.txt /srv/requirements.PRODUCTION.txt
RUN pip install -r /srv/requirements.PRODUCTION.txt

ENV DJANGO_ENVIRONMENT DEVELOPMENT

RUN python /app/manage.py collectstatic --noinput --clear

ENV DJANGO_ENVIRONMENT PRODUCTION