# ruff: noqa: F401
from .auth import AuthViewSet
from .bot import BotViewSet
from .bot_race import BotRaceViewSet
from .competition import CompetitionViewSet
from .competition_bot_map_stats import CompetitionBotMapStatsViewSet
from .competition_bot_matchup_stats import CompetitionBotMatchupStatsViewSet
from .competition_participation import CompetitionParticipationViewSet
from .discord_user import DiscordUserViewSet
from .game import GameViewSet
from .game_mode import GameModeViewSet
from .map import MapViewSet
from .map_pool import MapPoolViewSet
from .match import MatchViewSet
from .match_participation import MatchParticipationViewSet
from .match_requests import MatchRequestsViewSet
from .news import NewsViewSet
from .patreon_unlinked_discord_uid import PatreonUnlinkedDiscordUIDViewSet
from .result import ResultViewSet
from .round import RoundViewSet
from .user import UserViewSet
