# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 12:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DiscordInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('guild_name', models.CharField(blank=True, max_length=64)),
                ('guild_id', models.CharField(blank=True, max_length=20)),
                ('guild_icon', models.CharField(blank=True, max_length=32)),
                ('channel_name', models.CharField(blank=True, max_length=64)),
                ('channel_id', models.CharField(blank=True, max_length=20)),
                ('channel_type', models.CharField(blank=True, choices=[('text', 'text'), ('voice', 'voice')], max_length=5)),
                ('groups', models.ManyToManyField(blank=True, related_name='discord_invites', to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=254)),
                ('discriminator', models.CharField(max_length=4)),
                ('avatar', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('access_token', models.CharField(blank=True, max_length=32)),
                ('refresh_token', models.CharField(blank=True, max_length=32)),
                ('scope', models.CharField(blank=True, max_length=256)),
                ('expiry', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
