# Generated by Django 2.1.7 on 2019-03-16 23:25

from django.db import migrations


def seed_data(apps, schema_editor):
    # We can't import the Sc2Race model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Sc2Race = apps.get_model('core', 'Sc2Race')
    Sc2Race(name="Terran").save()
    Sc2Race(name="Zerg").save()
    Sc2Race(name="Protoss").save()
    Sc2Race(name="Random").save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
