# Generated by Django 2.1.7 on 2019-04-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_zip_md5hash',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
