# Generated by Django 2.1.7 on 2019-04-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190402_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='type',
            field=models.CharField(choices=[('Player1Win', 'Player1Win'), ('Player2Win', 'Player2Win'), ('Player1Crash', 'Player1Crash'), ('Player2Crash', 'Player2Crash'), ('GameTimeout', 'GameTimeout'), ('Tie', 'Tie')], max_length=12),
        ),
    ]
