# Generated by Django 3.0.8 on 2020-12-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201219_0827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Season',
            new_name='Competition',
        ),
    ]
