# Generated by Django 2.1.7 on 2019-04-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190419_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_won', to='core.Bot'),
        ),
    ]
