# Generated by Django 2.1.7 on 2019-04-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190419_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='type',
            field=models.CharField(choices=[('cppwin32', 'cppwin32'), ('cpplinux', 'cpplinux'), ('dotnetcore', 'dotnetcore'), ('java', 'java'), ('nodejs', 'nodejs'), ('python', 'python')], max_length=32),
        ),
        migrations.AlterField(
            model_name='result',
            name='type',
            field=models.CharField(choices=[('InitializationError', 'InitializationError'), ('Timeout', 'Timeout'), ('ProcessingReplay', 'ProcessingReplay'), ('Player1Win', 'Player1Win'), ('Player1Crash', 'Player1Crash'), ('Player1TimeOut', 'Player1TimeOut'), ('Player2Win', 'Player2Win'), ('Player2Crash', 'Player2Crash'), ('Player2Crash', 'Player2TimeOut'), ('Tie', 'Tie'), ('Error', 'Error')], max_length=32),
        ),
    ]
