# Generated by Django 3.0.8 on 2020-12-18 22:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_auto_20201219_0840"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SeasonParticipation",
            new_name="CompetitionParticipation",
        ),
    ]
