# Generated by Django 2.1.7 on 2019-04-24 07:12

from django.db import migrations, models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190419_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_zip',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='bots'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='type',
            field=models.CharField(choices=[('python', 'python')], max_length=32),
        ),
    ]
