# Generated by Django 2.1.7 on 2019-05-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_result_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='type',
            field=models.CharField(choices=[('InitializationError', 'InitializationError'), ('Timeout', 'Timeout'), ('ProcessingReplay', 'ProcessingReplay'), ('Player1Win', 'Player1Win'), ('Player1Crash', 'Player1Crash'), ('Player1TimeOut', 'Player1TimeOut'), ('Player2Win', 'Player2Win'), ('Player2Crash', 'Player2Crash'), ('Player2TimeOut', 'Player2TimeOut'), ('Tie', 'Tie'), ('Error', 'Error')], max_length=32),
        ),
    ]
