# Generated by Django 2.1.7 on 2019-05-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190504_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='resultant_elo',
            field=models.SmallIntegerField(null=True),
        ),
    ]
