# Generated by Django 3.0.8 on 2020-12-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_auto_20201225_0503"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamemode",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="gamemode",
            unique_together={("name", "game")},
        ),
    ]
