# Generated by Django 3.0.8 on 2020-12-24 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_auto_20201225_0553"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionparticipation",
            name="bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="competition_participations", to="core.Bot"
            ),
        ),
    ]
