# Generated by Django 2.1.7 on 2019-05-09 15:07

import aiarena.core.models
import aiarena.core.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields

from aiarena.core import models as core_models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190507_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bot_data',
            field=private_storage.fields.PrivateFileField(null=True, storage=aiarena.core.storage.OverwritePrivateStorage(base_url='/'), upload_to=core_models.bot.bot_data_upload_to),
        ),
        migrations.AddField(
            model_name='bot',
            name='bot_data_md5hash',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_zip',
            field=private_storage.fields.PrivateFileField(storage=aiarena.core.storage.OverwritePrivateStorage(base_url='/'), upload_to=core_models.bot.bot_zip_upload_to),
        ),
        migrations.AlterField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL),
        ),
    ]
