# Generated by Django 2.1.7 on 2019-05-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190510_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='replay_file',
            field=models.FileField(blank=True, null=True, upload_to='replays'),
        ),
    ]
