# Generated by Django 2.1.7 on 2019-05-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190513_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='in_match',
            field=models.BooleanField(default=False),
        ),
    ]
