# Generated by Django 2.1.7 on 2019-05-13 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190513_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='current_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Match'),
        ),
    ]
