# Generated by Django 3.0.8 on 2021-01-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_auto_20210106_1638"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "Created"),
                    ("frozen", "Frozen"),
                    ("paused", "Paused"),
                    ("open", "Open"),
                    ("closing", "Closing"),
                    ("closed", "Closed"),
                ],
                default="created",
                max_length=16,
            ),
        ),
    ]
