# Generated by Django 3.0.8 on 2021-01-15 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210108_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionparticipation',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.Competition'),
        ),
    ]
