# Generated by Django 2.1.7 on 2019-05-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190513_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='service_account',
            field=models.BooleanField(default=False),
        ),
    ]
