# Generated by Django 2.1.7 on 2019-05-14 15:46

import aiarena.core.models
import aiarena.core.storage
from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190513_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_data',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=aiarena.core.storage.OverwritePrivateStorage(base_url='/'), upload_to=aiarena.core.models.bot_data_upload_to),
        ),
        migrations.AlterField(
            model_name='bot',
            name='current_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bots_currently_in_match', to='core.Match'),
        ),
    ]
