# Generated by Django 3.0.8 on 2021-01-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210122_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='max_active_rounds',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
