# Generated by Django 2.1.7 on 2019-05-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190515_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bot_data_publicly_downloadable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bot',
            name='bot_zip_publicly_downloadable',
            field=models.BooleanField(default=False),
        ),
    ]
