# Generated by Django 3.0.8 on 2021-01-30 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_competition_max_active_rounds"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arenaclient",
            options={"verbose_name": "ArenaClient"},
        ),
    ]
