# Generated by Django 2.1.7 on 2019-05-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190518_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='winner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_won', to='core.Bot'),
        ),
    ]
