# Generated by Django 2.1.7 on 2019-05-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190520_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='elo_change',
            field=models.SmallIntegerField(null=True),
        ),
    ]
