# Generated by Django 2.1.7 on 2019-05-20 09:39
from django.db import migrations
from django.db.models import F


def copy_field(apps, schema_editor):
    MyModel = apps.get_model('core', 'Match')
    MyModel.objects.all().update(started=F('created'))


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0021_match_started'),
    ]

    operations = [
        migrations.RunPython(copy_field),
    ]
