# Generated by Django 2.1.7 on 2019-05-30 19:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_participant_elo_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='game_display_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_data_md5hash',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_zip_md5hash',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='result',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_won', to='core.Bot'),
        ),
    ]
