# Generated by Django 3.0.8 on 2021-02-05 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210205_0519'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='Tag',
    #         fields=[
    #             ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('name', models.CharField(max_length=32, unique=True)),
    #         ],
    #     ),
    #     migrations.CreateModel(
    #         name='MatchTag',
    #         fields=[
    #             ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tag')),
    #             ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
    #         ],
    #     ),
    #     migrations.AddField(
    #         model_name='match',
    #         name='tags',
    #         field=models.ManyToManyField(to='core.MatchTag'),
    #     ),
    # ]
