# Generated by Django 2.1.7 on 2019-06-01 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190531_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_data_md5hash',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_zip_md5hash',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
