# Generated by Django 3.0.8 on 2021-02-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_matchtags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="tags",
            field=models.ManyToManyField(blank=True, to="core.MatchTag"),
        ),
    ]
