# Generated by Django 3.0.8 on 2021-02-18 23:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_auto_20210217_0927"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebsiteNotice",
        ),
    ]
