# Generated by Django 2.1.7 on 2019-07-05 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_match_assigned_to'),
        ('core', '0022_auto_20190520_1909'),
    ]

    operations = [
    ]
