# Generated by Django 3.0.8 on 2021-03-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_websitenotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
