# Generated by Django 2.1.7 on 2019-07-05 20:06

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def createFirstRound(apps, schema_editor):
    Match = apps.get_model('core', 'Match')
    Round = apps.get_model('core', 'Round')
    if Match.objects.count() > 0:  # if there are existing matches, create a round for them
        Round.objects.create(complete=True, finished=timezone.now())


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0025_merge_20190706_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(createFirstRound),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Round'),
            preserve_default=False,
        ),
    ]
