# Generated by Django 3.0.8 on 2021-03-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_map_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="mappool",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
