# Generated by Django 3.0.8 on 2021-04-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_mappool_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionparticipation",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
