# Generated by Django 2.1.7 on 2019-07-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_result_realtime_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='average_step_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
