# Generated by Django 3.0.14 on 2021-07-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_auto_20210713_1146"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="interest",
            field=models.IntegerField(default=0),
        ),
    ]
