# Generated by Django 2.1.7 on 2019-07-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_participant_average_step_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='average_step_time',
            new_name='avg_step_time',
        ),
    ]
