# Generated by Django 2.1.7 on 2019-07-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_result_realtime_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsBotMatchups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_perc', models.FloatField()),
                ('win_count', models.IntegerField()),
                ('game_count', models.IntegerField()),
                ('generated_at', models.DateTimeField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bot')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_stats', to='core.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='StatsBots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_perc', models.FloatField()),
                ('crash_perc', models.FloatField()),
                ('game_count', models.IntegerField()),
                ('generated_at', models.DateTimeField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bot')),
            ],
        ),
    ]
