# Generated by Django 2.1.7 on 2019-07-25 20:27
import os

from django.db import migrations, connection

from aiarena.settings import SCRIPTS_ROOT


def run_usp_generate_stats_sql(apps, schema_editor):
    file_path = os.path.join(SCRIPTS_ROOT, 'usp_generate_stats.sql')
    sql_statement = open(file_path).read()
    with connection.cursor() as c:
        c.execute(sql_statement)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20190726_0547'),
    ]

    operations = [
        migrations.RunPython(run_usp_generate_stats_sql),
    ]
