# Generated by Django 2.1.7 on 2019-07-25 20:56

from django.db import migrations

from aiarena.scripts import run_usp_generate_stats_sql


def update_generate_stats(apps, schema_editor):
    run_usp_generate_stats_sql()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20190726_0557'),
    ]

    operations = [
        migrations.RunPython(update_generate_stats),
    ]
