# Generated by Django 3.0.14 on 2021-11-03 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_auto_20210926_0742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trophy",
            name="bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="trophies", to="core.Bot"
            ),
        ),
    ]
