# Generated by Django 2.1.7 on 2019-08-16 01:54

from django.db import migrations

from aiarena.scripts import run_usp_generate_stats_sql


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20190805_1915'),
    ]

    operations = [
        migrations.RunPython(run_usp_generate_stats_sql),
    ]
