# Generated by Django 3.2.9 on 2021-11-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arenaclientstatus",
            name="logged_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
