# Generated by Django 3.2.9 on 2022-02-15 06:10

import aiarena.core.models.competition_participation
import aiarena.core.storage
from django.db import migrations
import private_storage.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_alter_arenaclientstatus_logged_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionparticipation",
            name="elo_graph_update_plot",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=aiarena.core.storage.OverwritePrivateStorage(base_url="/"),
                upload_to=aiarena.core.models.competition_participation.elo_graph_update_plot_upload_to,
            ),
        ),
    ]
