# Generated by Django 3.2.9 on 2022-02-16 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_competition_wiki_article"),
        ("core", "0040_alter_arenaclientstatus_logged_at"),
    ]

    operations = []
