# Generated by Django 2.1.7 on 2019-08-20 07:38

import aiarena.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_statsbots_elo_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='avg_step_time',
            field=models.FloatField(blank=True, null=True, validators=[aiarena.core.validators.validate_not_nan, aiarena.core.validators.validate_not_inf]),
        ),
        migrations.AlterField(
            model_name='statsbotmatchups',
            name='win_perc',
            field=models.FloatField(validators=[aiarena.core.validators.validate_not_nan, aiarena.core.validators.validate_not_inf]),
        ),
        migrations.AlterField(
            model_name='statsbots',
            name='crash_perc',
            field=models.FloatField(validators=[aiarena.core.validators.validate_not_nan, aiarena.core.validators.validate_not_inf]),
        ),
        migrations.AlterField(
            model_name='statsbots',
            name='win_perc',
            field=models.FloatField(validators=[aiarena.core.validators.validate_not_nan, aiarena.core.validators.validate_not_inf]),
        ),
    ]
