# Generated by Django 2.1.7 on 2019-09-06 20:32

import aiarena.core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20190820_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\._\\-]*$', 'Only alphanumeric (A-Z, a-z, 0-9), period (.), underscore (_) and hyphen (-) characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='result',
            name='replay_file',
            field=models.FileField(blank=True, null=True, upload_to=aiarena.core.models.replay_file_upload_to),
        ),
        migrations.AlterField(
            model_name='result',
            name='type',
            field=models.CharField(choices=[('MatchCancelled', 'MatchCancelled'), ('InitializationError', 'InitializationError'), ('Timeout', 'Timeout'), ('ProcessingReplay', 'ProcessingReplay'), ('Player1Win', 'Player1Win'), ('Player1Crash', 'Player1Crash'), ('Player1TimeOut', 'Player1TimeOut'), ('Player1RaceMismatch', 'Player1RaceMismatch'), ('Player2Win', 'Player2Win'), ('Player2Crash', 'Player2Crash'), ('Player2TimeOut', 'Player2TimeOut'), ('Player2RaceMismatch', 'Player2RaceMismatch'), ('Tie', 'Tie'), ('Error', 'Error')], max_length=32),
        ),
    ]
