# Generated by Django 3.2.9 on 2022-02-22 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_serviceuser"),
        ("core", "0042_merge_20220222_2117"),
    ]

    operations = []
