# Generated by Django 3.2.9 on 2022-02-22 21:51

from django.db import migrations


def migrate_service_users(apps, schema_editor):
    pass  # migration broke and is no longer required
    # service_users = User.objects.filter(type="SERVICE")
    #
    # for service_user in service_users:
    #     # find parent class fields:
    #     fields = [f.name for f in User._meta.fields]
    #
    #     # get the values from the user instance
    #     values = dict([(x, getattr(service_user, x)) for x in fields])
    #
    #     new_instance = ServiceUser.objects.create(**values)
    #     new_instance.save()  # save new one


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_merge_0034_serviceuser_0042_merge_20220222_2117"),
    ]

    operations = [
        migrations.RunPython(migrate_service_users),
    ]
