# Generated by Django 3.2.9 on 2022-02-22 23:43

from django.db import migrations

from aiarena.core.models import Competition


def create_competition_wiki_articles(apps, schema_editor):
    for competition in Competition.objects.only("id").all():  # .only('id') avoids future conflicts
        competition.save()  # trigger the presave hook that creates the article


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_auto_20220222_2151"),
    ]

    operations = [
        migrations.RunPython(create_competition_wiki_articles),
    ]
