# Generated by Django 2.1.7 on 2019-09-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_user_patreon_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
