# Generated by Django 3.2.9 on 2022-02-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20220222_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionbotmatchupstats',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
