# Generated by Django 3.2.9 on 2022-05-23 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_competitionbotmapstats"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotRace",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "label",
                    models.CharField(
                        choices=[("T", "Terran"), ("Z", "Zerg"), ("P", "Protoss"), ("R", "Random")], max_length=1
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bot",
            name="plays_race_model",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="core.botrace"),
        ),
    ]
