# Generated by Django 3.2.9 on 2022-05-23 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20220523_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='plays_race',
        ),
    ]
