# Generated by Django 2.1.7 on 2019-10-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20191002_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='updated',
        ),
    ]
