# Generated by Django 2.1.7 on 2019-09-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_participant_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='result_cause',
            field=models.CharField(blank=True, choices=[('game_rules', 'Game Rules'), ('crash', 'Crash'), ('timeout', 'Timeout'), ('race_mismatch', 'Race Mismatch'), ('match_cancelled', 'Match Cancelled'), ('initialization_failure', 'Initialization Failure'), ('error', 'Error')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='result',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('win', 'Win'), ('loss', 'Loss'), ('tie', 'Tie')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='type',
            field=models.CharField(choices=[('MatchCancelled', 'MatchCancelled'), ('InitializationError', 'InitializationError'), ('Error', 'Error'), ('Player1Win', 'Player1Win'), ('Player1Crash', 'Player1Crash'), ('Player1TimeOut', 'Player1TimeOut'), ('Player1RaceMismatch', 'Player1RaceMismatch'), ('Player2Win', 'Player2Win'), ('Player2Crash', 'Player2Crash'), ('Player2TimeOut', 'Player2TimeOut'), ('Player2RaceMismatch', 'Player2RaceMismatch'), ('Tie', 'Tie')], max_length=32),
        ),
    ]
