# Generated by Django 3.2.9 on 2022-05-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_auto_20220523_0329"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='bot',
        #     name='plays_race_model',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.botrace'),
        # ),
    ]
