# Generated by Django 3.2.9 on 2022-05-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_alter_bot_plays_race_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botrace",
            name="label",
            field=models.CharField(
                choices=[("T", "Terran"), ("Z", "Zerg"), ("P", "Protoss"), ("R", "Random")], max_length=1, unique=True
            ),
        ),
    ]
