# Generated by Django 2.1.7 on 2019-10-06 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_bot_bot_zip_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discord_tag',
        ),
        migrations.RemoveField(
            model_name='user',
            name='discord_user',
        ),
    ]
