# Generated by Django 3.2.9 on 2022-06-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_alter_botrace_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="playable_races",
            field=models.ManyToManyField(blank=True, to="core.BotRace"),
        ),
    ]
