# Generated by Django 2.1.7 on 2019-10-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20191011_0227'),
        ('core', '0049_auto_20190927_0358'),
    ]

    operations = [
    ]
