# Generated by Django 2.1.7 on 2019-10-12 05:36

from django.db import migrations

from aiarena.scripts import run_usp_generate_stats_sql


def update_generate_stats(apps, schema_editor):
    run_usp_generate_stats_sql()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0053_auto_20191011_0323'),
    ]

    operations = [
        migrations.RunPython(update_generate_stats),
    ]
