# Generated by Django 3.2.9 on 2022-06-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20220613_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='plays_race_model',
            new_name='plays_race',
        ),
    ]
