# Generated by Django 3.2.9 on 2022-06-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_competition_playable_races'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='require_trusted_infrastructure',
            field=models.BooleanField(default=True),
        ),
    ]
