# Generated by Django 3.2.15 on 2022-09-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_rename_plays_race_model_bot_plays_race'),
        ('core', '0055_trusted_competition'),
    ]

    operations = [
    ]
