# Generated by Django 2.1.7 on 2019-10-18 07:18

from django.db import migrations, models
import django.db.models.deletion


def generate_bot_articles(apps, schema_editor):
    Bot = apps.get_model('core', 'Bot')
    for bot in Bot.objects.all():
        bot.save()  # this will cause the bot to auto generate a wiki article

class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_urlpath_moved_to'),
        ('core', '0055_auto_20191015_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='wiki_article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wiki.Article'),
        ),
        migrations.RunPython(generate_bot_articles),
        migrations.AlterField(
            model_name='bot',
            name='wiki_article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='wiki.Article'),
        ),
    ]
