# Generated by Django 3.2.9 on 2022-10-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_match_first_started'),
        ('core', '0055_trusted_competition'),
    ]

    operations = [
    ]
