# Generated by Django 2.1.7 on 2019-10-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20191013_0435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeasonElo',
            new_name='SeasonParticipation',
        ),
    ]
