# Generated by Django 3.2.9 on 2022-11-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_competitionparticipation_winrate_vs_duration_graph'),
        ('core', '0056_merge_20221001_1414'),
    ]

    operations = [
    ]
