# Generated by Django 2.1.7 on 2019-10-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20191013_0448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participation',
            new_name='MatchParticipation',
        ),
    ]
