# Generated by Django 2.1.7 on 2019-10-15 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20191013_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchparticipation',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Bot'),
        ),
    ]
