# Generated by Django 3.2.15 on 2022-12-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_merge_20221108_0651"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="statistics_finalized",
            field=models.BooleanField(default=False),
        ),
    ]
