# Generated by Django 2.1.7 on 2019-10-15 12:20

from django.db import migrations

from aiarena.scripts import run_usp_generate_stats_sql


def update_generate_stats(apps, schema_editor):
    run_usp_generate_stats_sql()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20191015_2033'),
    ]

    operations = [
        migrations.RunPython(update_generate_stats),
    ]
