# Generated by Django 2.1.7 on 2019-10-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20191015_0423'),
        ('core', '0059_auto_20191015_2250'),
    ]

    operations = [
    ]
