# Generated by Django 2.1.7 on 2019-10-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_merge_20191018_0351'),
        ('core', '0056_bot_wiki_article'),
    ]

    operations = [
    ]
