# Generated by Django 2.1.7 on 2019-10-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20190926_0229'),
        ('core', '0062_auto_20191024_0223'),
    ]

    operations = [
    ]
