# Generated by Django 2.1.7 on 2019-10-26 15:01

from django.db import migrations

from aiarena.core.models import Season


def open_first_season(apps, schema_editor):
    if Season.objects.count() == 1:
        season = Season.objects.get()
        if not season.is_open:
            season.open()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0063_merge_20191024_0244'),
    ]

    operations = [
        migrations.RunPython(open_first_season),
    ]
