# Generated by Django 2.1.7 on 2019-10-26 22:24

from django.db import migrations, models

from aiarena.core.models import Round


def update_round_numbers(apps, schema_editor):
    for round in Round.objects.all():
        round.number = round.id


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0064_auto_20191027_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='number',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.RunPython(update_round_numbers),
    ]
