# Generated by Django 2.1.7 on 2019-11-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20191027_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('WEBSITE_USER', 'Website User'), ('ARENA_CLIENT', 'Arena Client'), ('SERVICE', 'Service')], default='WEBSITE_USER', max_length=16),
        ),
    ]
