# Generated by Django 3.2.16 on 2023-01-08 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_botcrashlimitalert"),
        ("core", "0064_alter_competitionbotmapstats_unique_together"),
    ]

    operations = []
