# Generated by Django 3.2.16 on 2023-01-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_merge_20230108_1608'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionbotmatchupstats',
            unique_together={('bot', 'opponent')},
        ),
    ]
