# Generated by Django 2.1.7 on 2019-11-01 06:15

import aiarena.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('WEBSITE_USER', 'Website User'), ('ARENA_CLIENT', 'Arena Client'), ('SERVICE', 'Service')], default='WEBSITE_USER', max_length=16, validators=[aiarena.core.validators.validate_user_owner]),
        ),
    ]
