# Generated by Django 3.2.16 on 2023-01-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_alter_competitionbotmatchupstats_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionparticipation",
            name="participated_in_most_recent_round",
            field=models.BooleanField(default=False),
        ),
    ]
