# Generated by Django 3.2.16 on 2023-01-16 03:09

from django.db import migrations

from aiarena.core.models import Competition, CompetitionParticipation, Match
from aiarena.core.services import ladders


def mark_participated_in_most_recent_round(apps, schema_editor):
    for competition in Competition.objects.all().only("id"):
        last_round = ladders.get_most_recent_round(competition)
        if last_round is not None:
            bot_ids = (
                Match.objects.select_related("match_participation")
                .filter(round=last_round)
                .values("matchparticipation__bot__id")
                .distinct()
            )
            participants = ladders._get_competition_participants(competition).filter(
                bot__id__in=bot_ids, division_num__gte=CompetitionParticipation.MIN_DIVISION
            )

            for p in participants:
                p.participated_in_most_recent_round = True
                p.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_competitionparticipation_participated_in_most_recent_round"),
    ]

    operations = [
        migrations.RunPython(mark_participated_in_most_recent_round),
    ]
