# Generated by Django 2.1.7 on 2019-11-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20191107_2248'),
        ('core', '0066_season_number'),
    ]

    operations = [
    ]
