# Generated by Django 3.2.16 on 2023-01-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20230122_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionbotmatchupstats',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
