# Generated by Django 2.1.7 on 2019-11-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_merge_20191108_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='number',
            field=models.IntegerField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='season',
            name='number',
            field=models.IntegerField(blank=True, editable=False),
        ),
    ]
