# Generated by Django 3.2.16 on 2023-05-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0069_auto_20230122_1819"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="indepth_bot_statistics_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
