# Generated by Django 3.2.16 on 2023-02-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20230122_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='type',
            field=models.CharField(choices=[('cppwin32', 'CppWin32'), ('cpplinux', 'CppLinux'), ('dotnetcore', 'DotNetCore'), ('java', 'Java'), ('nodejs', 'NodeJS'), ('python', 'Python')], max_length=32),
        ),
    ]
