# Generated by Django 2.1.7 on 2019-11-10 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20191108_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('display', models.BooleanField(default=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='bot',
            name='current_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots_currently_in_match', to='core.Match'),
        ),
        migrations.AlterField(
            model_name='seasonparticipation',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bot'),
        ),
    ]
