# Generated by Django 3.2.16 on 2023-09-19 14:12

from django.db import migrations, models

import private_storage.fields
import private_storage.storage.files

import aiarena.core.models.bot
import aiarena.core.models.competition_participation
import aiarena.core.models.map
import aiarena.core.models.match_participation


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0071_alter_bot_bot_zip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="bot_data",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to=aiarena.core.models.bot.bot_data_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="bot_zip",
            field=private_storage.fields.PrivateFileField(
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to=aiarena.core.models.bot.bot_zip_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="competitionparticipation",
            name="elo_graph",
            field=models.FileField(
                blank=True, null=True, upload_to=aiarena.core.models.competition_participation.elo_graph_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="competitionparticipation",
            name="elo_graph_update_plot",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to=aiarena.core.models.competition_participation.elo_graph_update_plot_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="competitionparticipation",
            name="winrate_vs_duration_graph",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=aiarena.core.models.competition_participation.winrate_vs_duration_graph_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="map",
            name="file",
            field=models.FileField(upload_to=aiarena.core.models.map.map_file_upload_to),
        ),
        migrations.AlterField(
            model_name="matchparticipation",
            name="match_log",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to=aiarena.core.models.match_participation.match_log_upload_to,
            ),
        ),
    ]
