# Generated by Django 2.1.7 on 2019-11-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_match_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_active_bots_per_race',
            field=models.IntegerField(default=0),
        ),
    ]
