# Generated by Django 3.2.16 on 2023-10-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_remove_override_storage_from_filefields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchparticipation',
            name='participant_number',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
