# Generated by Django 2.1.7 on 2019-11-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_user_extra_active_bots_per_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='previous_season_replays_cleaned',
            field=models.BooleanField(default=False),
        ),
    ]
