# Generated by Django 2.1.7 on 2019-11-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_season_previous_season_replays_cleaned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='previous_season_replays_cleaned',
            new_name='previous_season_files_cleaned',
        ),
    ]
