# Generated by Django 2.1.7 on 2019-11-26 20:15

from django.db import migrations, models


from aiarena.core import models as core_models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20191127_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='replay_archive_zip',
            field=models.FileField(default=(), upload_to=core_models.season.replay_archive_upload_to),
        ),
    ]
