# Generated by Django 2.1.7 on 2019-11-26 20:15

import aiarena.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20191127_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='replay_archive_zip',
            field=models.FileField(default=(), upload_to=aiarena.core.models.replay_archive_upload_to),
        ),
    ]
