# Generated by Django 2.1.7 on 2019-11-30 18:46

import aiarena.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_season_replay_archive_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_email_comms',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='replay_archive_zip',
            field=models.FileField(blank=True, null=True, upload_to=aiarena.core.models.replay_archive_upload_to),
        ),
    ]
