# Generated by Django 4.2.16 on 2024-12-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0078_remove_user_can_request_games_for_another_authors_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="map_file_extension",
            field=models.CharField(default=".SC2Map", max_length=20),
        ),
    ]
