# Generated by Django 4.2.16 on 2025-03-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0079_game_map_file_extension"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="map_file_extension",
            field=models.CharField(
                default=".SC2Map", help_text="The file extension to use for map files for this game", max_length=20
            ),
        ),
    ]
