# Generated by Django 2.1.7 on 2019-12-06 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20191204_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='extra_requested_matches_per_week',
            new_name='extra_periodic_match_requests',
        ),
    ]
