# Generated by Django 2.1.7 on 2020-01-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_trophy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trophy',
            old_name='bot_data_md5hash',
            new_name='name',
        ),
    ]
