# Generated by Django 2.1.7 on 2020-01-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_auto_20200101_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophy',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
