# Generated by Django 4.2.20 on 2025-08-03 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0082_alter_competitionparticipation_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="type",
        ),
    ]
