# Generated by Django 4.2.24 on 2025-11-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0083_remove_competition_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="matchparticipation",
            index=models.Index(fields=["bot", "-id"], name="core_matchpart_bot_id_desc"),
        ),
        # The difference is that a direct bot_id column is added
        migrations.RunSQL(
            """
                drop view if exists core_relativeresult;
                create view core_relativeresult as
                    select cr.id as id,
                    me_mp.id as me_id,
                    me_mp.bot_id as bot_id,
                    cm.id as match_id,
                    cm.started as started,
                    opponent_mp.id as opponent_id,
                    me_mp.result as result,
                    me_mp.result_cause as result_cause,
                    me_mp.elo_change as elo_change,
                    me_mp.avg_step_time as avg_step_time,
                    to_char( (cr.game_steps/22.4 ||' seconds')::interval, 'HH24:MI:SS' ) as game_time_formatted,
                    cr.game_steps as game_steps,
                            cr.replay_file as replay_file,
                            me_mp.match_log as match_log
                    from core_result cr
                    join core_match cm on cr.id = cm.result_id
                    join core_matchparticipation me_mp on cm.id = me_mp.match_id
                    join core_matchparticipation opponent_mp on cm.id = opponent_mp.match_id and me_mp.participant_number!=opponent_mp.participant_number
        """
        ),
    ]
