# Generated by Django 4.2.29 on 2026-03-22 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_matchparticipation_core_matchpart_bot_id_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryUpload",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    private_storage.fields.PrivateFileField(
                        storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to="temp-uploads/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
