# Generated by Django 4.2.29 on 2026-05-15 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_temporary_upload"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiUsage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("call_count", models.PositiveIntegerField()),
                ("total_duration_ms", models.PositiveBigIntegerField()),
                ("p50_duration_ms", models.PositiveIntegerField()),
                ("p75_duration_ms", models.PositiveIntegerField()),
                ("p95_duration_ms", models.PositiveIntegerField()),
                ("p99_duration_ms", models.PositiveIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["period_end"], name="core_apiusa_period__32b573_idx")],
                "unique_together": {("user", "period_start", "period_end")},
            },
        ),
    ]
