# Generated by Django 4.2.29 on 2026-05-15 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0086_apiusage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arenaclientstatus",
            options={"verbose_name_plural": "Arena client statuses"},
        ),
        migrations.AlterModelOptions(
            name="competitionbotmapstats",
            options={"verbose_name_plural": "Competition bot map stats"},
        ),
        migrations.AlterModelOptions(
            name="competitionbotmatchupstats",
            options={"verbose_name_plural": "Competition bot matchup stats"},
        ),
    ]
