# Generated by Django 2.1.7 on 2020-01-04 00:58

import aiarena.core.models.season_participation
import aiarena.core.storage
import aiarena.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_result_date_interest_rating_calculated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsbots',
            name='bot',
        ),
        migrations.AddField(
            model_name='seasonparticipation',
            name='crash_perc',
            field=models.FloatField(blank=True, null=True, validators=[aiarena.core.validators.validate_not_nan, aiarena.core.validators.validate_not_inf]),
        ),
        migrations.AddField(
            model_name='seasonparticipation',
            name='elo_graph',
            field=models.FileField(blank=True, null=True, storage=aiarena.core.storage.OverwriteStorage(), upload_to=aiarena.core.models.season_participation.elo_graph_upload_to),
        ),
        migrations.AddField(
            model_name='seasonparticipation',
            name='game_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonparticipation',
            name='win_perc',
            field=models.FloatField(blank=True, null=True, validators=[aiarena.core.validators.validate_not_nan, aiarena.core.validators.validate_not_inf]),
        ),
        migrations.DeleteModel(
            name='StatsBots',
        ),
    ]
