# Generated by Django 2.1.7 on 2020-01-04 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20200104_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonparticipation',
            old_name='game_count',
            new_name='match_count',
        ),
    ]
