# Generated by Django 4.2.29 on 2026-08-16 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0087_alter_arenaclientstatus_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardSet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="competition",
            name="awards_given",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trophy",
            name="competition_participation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trophies",
                to="core.competitionparticipation",
            ),
        ),
        migrations.AddField(
            model_name="trophy",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_place", "1st Place"),
                    ("second_place", "2nd Place"),
                    ("third_place", "3rd Place"),
                    ("top_5", "Top 5"),
                    ("top_10", "Top 10"),
                    ("top_15", "Top 15"),
                    ("top_20", "Top 20"),
                    ("best_zerg", "Best Zerg"),
                    ("best_protoss", "Best Protoss"),
                    ("best_terran", "Best Terran"),
                    ("best_random", "Best Random"),
                    ("participant", "Participant"),
                    ("custom", "Custom"),
                ],
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="award_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="competitions",
                to="core.awardset",
            ),
        ),
        migrations.CreateModel(
            name="AwardSetItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("first_place", "1st Place"),
                            ("second_place", "2nd Place"),
                            ("third_place", "3rd Place"),
                            ("top_5", "Top 5"),
                            ("top_10", "Top 10"),
                            ("top_15", "Top 15"),
                            ("top_20", "Top 20"),
                            ("best_zerg", "Best Zerg"),
                            ("best_protoss", "Best Protoss"),
                            ("best_terran", "Best Terran"),
                            ("best_random", "Best Random"),
                            ("participant", "Participant"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "award_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="core.awardset"
                    ),
                ),
                (
                    "trophy_icon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="award_set_items",
                        to="core.trophyicon",
                    ),
                ),
            ],
            options={
                "unique_together": {("award_set", "condition")},
            },
        ),
    ]
