# Generated by Django 4.2.29 on 2026-08-06 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0087_alter_arenaclientstatus_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardSet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="competition",
            name="awards_given",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trophy",
            name="competition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trophies",
                to="core.competition",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("date_viewed", models.DateTimeField(blank=True, null=True)),
                ("date_created", models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                (
                    "decal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="core.trophyicon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
        migrations.AddField(
            model_name="competition",
            name="award_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="competitions",
                to="core.awardset",
            ),
        ),
        migrations.CreateModel(
            name="AwardSetItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("first_place", "First Place"),
                            ("second_place", "Second Place"),
                            ("third_place", "Third Place"),
                            ("top_10", "Top 10"),
                            ("top_15", "Top 15"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "award_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="core.awardset"
                    ),
                ),
                (
                    "trophy_icon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="award_set_items",
                        to="core.trophyicon",
                    ),
                ),
            ],
            options={
                "unique_together": {("award_set", "condition")},
            },
        ),
    ]
