# Generated by Django 4.2.29 on 2026-09-18 18:01

from django.db import migrations, models

import aiarena.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0088_awardset_competition_awards_given_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="bot1_args",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                null=True,
                validators=[aiarena.core.validators.validate_bot_args],
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="bot2_args",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                null=True,
                validators=[aiarena.core.validators.validate_bot_args],
            ),
        ),
    ]
