# Generated by Django 2.1.7 on 2020-01-04 02:25

from django.db import migrations, models
from django.utils.text import slugify


def set_sp_slugs(apps, schema_editor):
    SeasonParticipation = apps.get_model('core', 'SeasonParticipation')
    for sp in SeasonParticipation.objects.all():
        sp.slug = slugify(f'{sp.bot.name} Season {sp.season.number}')
        sp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_auto_20200104_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonparticipation',
            name='slug',
            field=models.SlugField(null=True, max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(set_sp_slugs),
        migrations.AlterField(
            model_name='seasonparticipation',
            name='slug',
            field=models.SlugField(max_length=255),
            preserve_default=False,
        ),
    ]
