# Generated by Django 4.2.29 on 2026-08-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0088_awardset_competition_awards_given_trophy_competition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awardsetitem",
            name="condition",
            field=models.CharField(
                choices=[
                    ("first_place", "First Place"),
                    ("second_place", "Second Place"),
                    ("third_place", "Third Place"),
                    ("top_3", "Top 3"),
                    ("top_5", "Top 5"),
                    ("top_10", "Top 10"),
                    ("top_15", "Top 15"),
                    ("top_20", "Top 20"),
                    ("participant", "Participant"),
                    ("custom", "Custom"),
                ],
                max_length=32,
            ),
        ),
    ]
