# Generated by Django 4.2.29 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0088_awardset_competition_awards_given_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="division_sizing_mode",
            field=models.CharField(
                choices=[("manual", "Manual"), ("automatic", "Automatic (~20 bots per division)")],
                default="manual",
                max_length=16,
            ),
        ),
    ]
