# Generated by Django 4.2.29 on 2026-08-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0089_alter_awardsetitem_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="trophy",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("top_1", "1st Place"),
                    ("top_2", "2nd Place"),
                    ("top_3", "3rd Place"),
                    ("top_5", "Top 5"),
                    ("top_10", "Top 10"),
                    ("top_15", "Top 15"),
                    ("top_20", "Top 20"),
                    ("participant", "Participant"),
                    ("custom", "Custom"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="awardsetitem",
            name="condition",
            field=models.CharField(
                choices=[
                    ("top_1", "1st Place"),
                    ("top_2", "2nd Place"),
                    ("top_3", "3rd Place"),
                    ("top_5", "Top 5"),
                    ("top_10", "Top 10"),
                    ("top_15", "Top 15"),
                    ("top_20", "Top 20"),
                    ("participant", "Participant"),
                    ("custom", "Custom"),
                ],
                max_length=32,
            ),
        ),
    ]
