# Generated by Django 2.1.7 on 2020-01-04 18:41

import aiarena.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_seasonparticipation_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonBotMatchupStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_perc', models.FloatField(validators=[aiarena.core.validators.validate_not_nan, aiarena.core.validators.validate_not_inf])),
                ('win_count', models.IntegerField()),
                ('game_count', models.IntegerField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bot')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_stats', to='core.Bot')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Season')),
            ],
        ),
        migrations.RemoveField(
            model_name='statsbotmatchups',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='statsbotmatchups',
            name='opponent',
        ),
        migrations.DeleteModel(
            name='StatsBotMatchups',
        ),
    ]
