# Generated by Django 4.2.29 on 2026-08-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_trophy_condition_alter_awardsetitem_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardsetitem',
            name='condition',
            field=models.CharField(choices=[('first_place', '1st Place'), ('second_place', '2nd Place'), ('third_place', '3rd Place'), ('top_5', 'Top 5'), ('top_10', 'Top 10'), ('top_15', 'Top 15'), ('top_20', 'Top 20'), ('best_zerg', 'Best Zerg'), ('best_protoss', 'Best Protoss'), ('best_terran', 'Best Terran'), ('best_random', 'Best Random'), ('participant', 'Participant'), ('custom', 'Custom')], max_length=32),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='condition',
            field=models.CharField(blank=True, choices=[('first_place', '1st Place'), ('second_place', '2nd Place'), ('third_place', '3rd Place'), ('top_5', 'Top 5'), ('top_10', 'Top 10'), ('top_15', 'Top 15'), ('top_20', 'Top 20'), ('best_zerg', 'Best Zerg'), ('best_protoss', 'Best Protoss'), ('best_terran', 'Best Terran'), ('best_random', 'Best Random'), ('participant', 'Participant'), ('custom', 'Custom')], max_length=64),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
