# Generated by Django 2.1.7 on 2020-01-04 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_auto_20200105_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonbotmatchupstats',
            old_name='game_count',
            new_name='match_count',
        ),
        migrations.AlterField(
            model_name='seasonbotmatchupstats',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_stats', to='core.SeasonParticipation'),
        ),
    ]
