# Generated by Django 4.2.29 on 2026-08-16 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_awardsetitem_condition_alter_trophy_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trophy',
            name='competition',
        ),
        migrations.AddField(
            model_name='trophy',
            name='competition_participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trophies', to='core.competitionparticipation'),
        ),
    ]
