# Generated by Django 2.1.7 on 2020-01-04 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_auto_20200105_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonbotmatchupstats',
            name='season',
        ),
        migrations.AlterField(
            model_name='seasonbotmatchupstats',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SeasonParticipation'),
        ),
    ]
