# Generated by Django 2.1.7 on 2020-01-04 20:38

import aiarena.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_auto_20200105_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonbotmatchupstats',
            name='match_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasonbotmatchupstats',
            name='win_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasonbotmatchupstats',
            name='win_perc',
            field=models.FloatField(blank=True, null=True, validators=[aiarena.core.validators.validate_not_nan, aiarena.core.validators.validate_not_inf]),
        ),
    ]
