# Generated by Django 2.1.7 on 2020-01-04 20:45

import aiarena.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_auto_20200105_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonbotmatchupstats',
            name='crash_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonbotmatchupstats',
            name='crash_perc',
            field=models.FloatField(blank=True, null=True, validators=[aiarena.core.validators.validate_not_nan, aiarena.core.validators.validate_not_inf]),
        ),
        migrations.AddField(
            model_name='seasonbotmatchupstats',
            name='loss_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonbotmatchupstats',
            name='loss_perc',
            field=models.FloatField(blank=True, null=True, validators=[aiarena.core.validators.validate_not_nan, aiarena.core.validators.validate_not_inf]),
        ),
        migrations.AddField(
            model_name='seasonbotmatchupstats',
            name='tie_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonbotmatchupstats',
            name='tie_perc',
            field=models.FloatField(blank=True, null=True, validators=[aiarena.core.validators.validate_not_nan, aiarena.core.validators.validate_not_inf]),
        ),
    ]
