# Generated by Django 2.1.7 on 2020-01-04 21:16

import aiarena.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20200105_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonparticipation',
            name='crash_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonparticipation',
            name='loss_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonparticipation',
            name='loss_perc',
            field=models.FloatField(blank=True, null=True, validators=[aiarena.core.validators.validate_not_nan, aiarena.core.validators.validate_not_inf]),
        ),
        migrations.AddField(
            model_name='seasonparticipation',
            name='tie_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonparticipation',
            name='tie_perc',
            field=models.FloatField(blank=True, null=True, validators=[aiarena.core.validators.validate_not_nan, aiarena.core.validators.validate_not_inf]),
        ),
        migrations.AddField(
            model_name='seasonparticipation',
            name='win_count',
            field=models.IntegerField(default=0),
        ),
    ]
