# Generated by Django 2.1.7 on 2020-01-04 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20200105_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonbotmatchupstats',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_matchup_stats', to='core.SeasonParticipation'),
        ),
        migrations.AlterField(
            model_name='seasonbotmatchupstats',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_matchup_stats', to='core.SeasonParticipation'),
        ),
    ]
