# Generated by Django 2.1.7 on 2020-01-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_auto_20200105_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonparticipation',
            name='highest_elo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
