# Generated by Django 2.1.7 on 2020-02-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_seasonparticipation_highest_elo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='current_match',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='in_match',
        ),
        migrations.AddField(
            model_name='bot',
            name='bot_data_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matchparticipation',
            name='update_bot_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matchparticipation',
            name='use_bot_data',
            field=models.BooleanField(default=True),
        ),
    ]
