# Generated by Django 2.1.7 on 2020-03-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_seasonparticipation_highest_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_request_games_for_another_authors_bot',
            field=models.BooleanField(default=False),
        ),
    ]
