# Generated by Django 2.1.7 on 2020-03-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_user_can_request_games_for_another_authors_bot'),
        ('core', '0098_auto_20200207_0456'),
    ]

    operations = [
    ]
