# Generated by Django 2.1.7 on 2020-03-08 18:43

import django.db.models.deletion
from django.db import migrations, models

from aiarena.core.models import Season
from aiarena.core.models.competition import Competition


def create_melee_ladder(apps, schema_editor):
    if Season.objects.count() > 0:  # if there are existing seasons, create a ladder for them
        Competition.objects.create(name='Melee', type='ladder')


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0099_merge_20200309_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('ladder', 'Ladder'), ('tournament', 'Tournament'),
                                                   ('flash_challenge', 'Flash Challenge')], max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='competition',
            field=models.ManyToManyField(to='core.Competition'),
        ),
        migrations.AddField(
            model_name='season',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='core.Competition'),
        ),

        migrations.RunPython(create_melee_ladder),
        migrations.AlterField(
            model_name='season',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Competition'),
            preserve_default=False,
        ),
    ]
