# Generated by Django 2.1.7 on 2020-03-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_auto_20200309_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='active',
        ),
        migrations.RemoveField(
            model_name='seasonparticipation',
            name='bot',
        ),
        migrations.AddField(
            model_name='seasonparticipation',
            name='bot',
            field=models.ManyToManyField(to='core.Bot'),
        ),
    ]
