# Generated by Django 2.1.7 on 2020-05-01 22:51

import aiarena.core.models.bot
from django.db import migrations, models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_auto_20200425_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_data',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(base_url='/'), upload_to=aiarena.core.models.bot.bot_data_upload_to),
        ),
        migrations.AlterField(
            model_name='match',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='started',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='game_steps',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='interest_rating',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='type',
            field=models.CharField(choices=[('MatchCancelled', 'MatchCancelled'), ('InitializationError', 'InitializationError'), ('Error', 'Error'), ('Player1Win', 'Player1Win'), ('Player1Crash', 'Player1Crash'), ('Player1TimeOut', 'Player1TimeOut'), ('Player1RaceMismatch', 'Player1RaceMismatch'), ('Player1Surrender', 'Player1Surrender'), ('Player2Win', 'Player2Win'), ('Player2Crash', 'Player2Crash'), ('Player2TimeOut', 'Player2TimeOut'), ('Player2RaceMismatch', 'Player2RaceMismatch'), ('Player2Surrender', 'Player2Surrender'), ('Tie', 'Tie')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='round',
            name='finished',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='started',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
