# Generated by Django 2.1.7 on 2020-05-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_arenaclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='require_trusted_arenaclient',
            field=models.BooleanField(default=True),
        ),
    ]
