# Generated by Django 2.1.7 on 2020-05-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_match_require_trusted_arenaclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='replay_archive_zip',
        ),
    ]
