# Generated by Django 2.1.7 on 2020-06-22 09:11

import aiarena.core.models.bot
import aiarena.core.storage
import aiarena.core.validators
from django.db import migrations, models
import private_storage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_relativeresult'),
    ]

    operations = [
        # Broken migrations - field removed
        # migrations.AddField(
        #     model_name='bot',
        #     name='is_probots_participant',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='bot',
        #     name='probots_bot_data',
        #     field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=aiarena.core.storage.OverwritePrivateStorage(base_url='/'), upload_to=aiarena.core.models.bot.probots_bot_data_upload_to),
        # ),
        # migrations.AddField(
        #     model_name='bot',
        #     name='probots_bot_zip',
        #     field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=aiarena.core.storage.OverwritePrivateStorage(base_url='/'), upload_to=aiarena.core.models.bot.probots_bot_zip_upload_to, validators=[aiarena.core.validators.validate_bot_zip_file]),
        # ),
    ]
