# Generated by Django 2.1.7 on 2020-06-22 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_auto_20200622_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='probots_update_deadline',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
