# Generated by Django 2.1.7 on 2020-06-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_bot_probots_update_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='probots_update_deadline',
        ),
    ]
