# Generated by Django 2.1.7 on 2020-07-06 01:33

import aiarena.core.models.bot
import aiarena.core.storage
from django.db import migrations
import private_storage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_remove_bot_probots_update_deadline'),
    ]

    operations = [
        # Broken migration - field removed
        # migrations.AddField(
        #     model_name='bot',
        #     name='probots_bot_source',
        #     field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=aiarena.core.storage.OverwritePrivateStorage(base_url='/'), upload_to=aiarena.core.models.bot.probots_bot_source_upload_to),
        # ),
    ]
