# Generated by Django 2.1.7 on 2020-07-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_auto_20200626_0413'),
        ('core', '0110_bot_probots_bot_source'),
    ]

    operations = [
    ]
