# Generated by Django 3.0.8 on 2020-08-20 10:40

import aiarena.core.models.bot
import aiarena.core.storage
import aiarena.core.validators
from django.db import migrations, models
import private_storage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_merge_20200708_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='secrets_config',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='probots_bot_data',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=aiarena.core.storage.HardcodedURLFilenamePrivateStorage(base_url='/', url_filename='bot_data'), upload_to=aiarena.core.models.bot.probots_bot_data_upload_to),
        ),
        migrations.AlterField(
            model_name='bot',
            name='probots_bot_source',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=aiarena.core.storage.HardcodedURLFilenamePrivateStorage(base_url='/', url_filename='bot_source'), upload_to=aiarena.core.models.bot.probots_bot_source_upload_to),
        ),
        migrations.AlterField(
            model_name='bot',
            name='probots_bot_zip',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=aiarena.core.storage.HardcodedURLFilenamePrivateStorage(base_url='/', url_filename='bot_zip'), upload_to=aiarena.core.models.bot.probots_bot_zip_upload_to, validators=[aiarena.core.validators.validate_bot_zip_file]),
        ),
    ]
