# Generated by Django 3.0.8 on 2020-09-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_auto_20200919_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='owner',
        ),
        migrations.RenameField(
            model_name='arenaclient',
            old_name='ac_owner',
            new_name='owner',
        ),
    ]
