# Generated by Django 3.0.8 on 2020-09-21 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_remove_user_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaClientStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('starting_game', 'Starting Game'), ('playing_game', 'In Game'), ('submitting_result', 'Submitting Result')], max_length=17)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('arenaclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='core.ArenaClient')),
            ],
        ),
    ]
