# Generated by Django 3.0.8 on 2020-09-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_auto_20200922_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sync_patreon_status',
            field=models.BooleanField(default=True),
        ),
    ]
