# Generated by Django 3.0.8 on 2020-10-09 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_user_sync_patreon_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonbotmatchupstats',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='seasonbotmatchupstats',
            name='opponent',
        ),
        migrations.AddField(
            model_name='seasonbotmatchupstats',
            name='bot1',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='bot1', to='core.Bot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seasonbotmatchupstats',
            name='bot2',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='bot2', to='core.Bot'),
            preserve_default=False,
        ),
    ]
