# Generated by Django 3.0.8 on 2020-10-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_user_supported_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='supported_expiration_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
