# Generated by Django 3.0.8 on 2020-11-12 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_auto_20201112_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='replay_archive_zip',
        ),
        migrations.AddField(
            model_name='seasonbotmatchupstats',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
