# Generated by Django 3.0.8 on 2020-11-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_seasonbotmatchupstats_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
    ]
