# Generated by Django 3.0.8 on 2020-11-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_seasonbotmatchupstats_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonparticipation',
            name='trend_comparison_elo',
            field=models.SmallIntegerField(default=1600),
        ),
    ]
