# Generated by Django 3.0.8 on 2020-10-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_auto_20201018_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='supporter_level',
            field=models.CharField(choices=[('none', 'None'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='none', max_length=16),
        ),
    ]
