# Generated by Django 3.0.8 on 2020-11-23 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_auto_20201124_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrophyIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('image', models.ImageField(upload_to='trophy_images/')),
            ],
        ),
        migrations.AddField(
            model_name='trophy',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.TrophyIcon'),
        ),
    ]
