# Generated by Django 3.0.8 on 2020-11-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_auto_20201112_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='competition',
            new_name='competitions',
        ),
    ]
