name: backup
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  DJANGO_ENVIRONMENT: DEVELOPMENT
  PYTHONUNBUFFERED: 1

jobs:
  backup:
    name: Backup production DB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::315513665747:role/aiarena-DeployRole-NUZWXPWHC0MZ
          aws-region: eu-central-1

      - name: Confirm AWS identity
        run: aws sts get-caller-identity

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Perform production DB backup
        run: uv run run.py production-backup

